# spring
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: developer
    password: Qx310320.n
    url: jdbc:mysql://121.41.115.29:3306/kexie_open_judge?useUnicode=true&characterEncoding=UTF-8
  data:
    redis:
      host: 121.41.115.29
      database: 0
      port: 6379
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1
          max-idle: 8
          min-idle: 0
# mybatis-flex
mybatis-flex:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    print-banner: false
  type-aliases-package: com.fish.entity

logging:
  level:
    com.fish.mapper: debug

jwt:
  secret: b474a99a2705e23cf905a484ec6d14ef58b56bbe62e9292783466ec363b5072d
  expireTime: 10080
  header: Authorization
  year: 2023